name: Update FearProject servers

on:
  schedule:
    - cron: "*/5 * * * *"

  workflow_dispatch:

permissions:
  contents: write

jobs:

  update:

    runs-on: ubuntu-latest

    steps:

      - name: Checkout
        uses: actions/checkout@v4

      - name: Download servers.json
        run: |
          curl \
            --fail \
            --location \
            --silent \
            --show-error \
            --retry 3 \
            "https://fearproject.ru/api/servers" \
            -o servers.json

      - name: Validate JSON
        run: |
          python3 -m json.tool servers.json > /dev/null

      - name: Commit changes
        run: |

          git config user.name "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"

          git add servers.json

          if git diff --cached --quiet; then
            echo "No changes."
            exit 0
          fi

          git commit -m "chore: update servers.json"
          git push
